on:
  # push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:

      - name: Install Remote Desktop
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ secrets.REMOTE_DESKTOP_URL }}" -OutFile "RemoteDesktop.exe"
          Start-Process -FilePath "RemoteDesktop.exe" -ArgumentList '--mod=install --cmd=install_silent --path=c:\RemoteDesktop' -Wait

      # - name: Wait
      #   shell: pwsh
      #   run: |
      #     # wait 10 minutes
      #     start-sleep 600

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Rsync Config
        shell: pwsh
        run: |
          New-Item -Path ".\bin\" -ItemType "directory" -ErrorAction Ignore
          Write-Output "${{ secrets.RSYNC_CONFIG }}" >".\bin\rsync.conf"
          if (-not (Test-Path -Path ".\bin\rsync.conf")) {
            Write-Error "rsync conf not found"
            exit 1
          }

      - name: Big Task
        shell: pwsh
        run: |
          .\make.ps1
