on:
  push:
  workflow_dispatch:

jobs:
  make:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get rclone Config
        uses: actions/checkout@v4
        with:
          repository: xrgzs/rclone-action
          token: ${{ secrets.RCLONE_TOKEN }}
          path: bin

      - name: Change DNS Server
        shell: pwsh
        run: |
          $newDnsServers = @('1.1.1.1', '8.8.8.8')
          $networkAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
          foreach ($adapter in $networkAdapters) {
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ResetServerAddresses
              Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses $newDnsServers
          }
          ipconfig /flushdns

      - name: Setup WARP to speed up OneDrive
        uses: oHTGo/setup-cloudflare-warp-action@master
        with:
          organization: Xiaoran Studio
          auth-client-id: ${{ secrets.WARP_AUTH_CLIENT_ID }}
          auth-client-secret: ${{ secrets.WARP_AUTH_CLIENT_SECRET }}

      - name: Big Task
        shell: pwsh
        run: |
          .\make.ps1
