on:
  push:
  workflow_dispatch:

jobs:
  make:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get rclone Config
        uses: actions/checkout@v4
        with:
          repository: xrgzs/rclone-action
          token: ${{ secrets.RCLONE_TOKEN }}
          path: bin

      - name: Big Task
        shell: pwsh
        run: |
          .\make.ps1
