on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Output system information
        shell: pwsh
        run: |
          $PSVersionTable
          Get-ComputerInfo
